name: UnitedWar
version: '${project.version}'
main: org.unitedlands.war.UnitedWar
api-version: 1.21
description: A custom war plugin for United Lands.
authors: [ Litning11, Theriel_]
depend: [ Towny ]
softdepend: [ AngelChest, AxGraves, MapTowny ]
commands:
  wardebug:
     description: Debugging commands.
     permission: united.war.admin
     aliases: [wd]
  waradmin:
     description: War Admin commands.
     permission: united.war.admin
     aliases: [wa]
